### ISSUE TITLE
Auto Deployment to Github pages

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/rights-editor#11]
**Für automatisches Deployment eures Github Repos**:
1. Einen neuen Branch anlegen und in diesem eine `.travis.yml` im root Ordner des Projekts anlegen
1.1. die `.travis.yml` mit diesem Inhalt füllen:
```
language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  local-dir: "dist"
  allow-empty-commit: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
```
2. einen Pull_Request des neuen Branchs auf den master anlegen (ABER NICHT MERGEN!)
3. Auf https://travis-ci.com/ in den Einstellungen `Build Pushed Branches` aktivieren (https://travis-ci.com/schul-cloud/rights-editor).
3.1.
![image](https://user-images.githubusercontent.com/22987140/52712924-51791380-2f96-11e9-889d-fc6c08c53498.png)
3.2. ![image](https://user-images.githubusercontent.com/22987140/52712962-69e92e00-2f96-11e9-8b15-9fb82e194bdb.png)
3.3. (optional) könnt ihr unten in den Einstellungen noch aktivieren, dass in regelmäßigen abständen auf dem master erneut ein build (und somit deployment) ausgeführt werden soll.
4. In den Travis Einstellungen einen Github Token hinterlegen (`show value in build log` sollte keinesfalls für diesen token aktiviert werden). Der Token kann unter https://github.com/settings/tokens erstellt werden.
![image](https://user-images.githubusercontent.com/22987140/52713156-dcf2a480-2f96-11e9-931d-b2cecd0f699d.png)
5. Den Pull mit der .travis.yml mergen
6. In den Einstellungen eures Repos `gh-pages branch` als Branch auswählen
![image](https://user-images.githubusercontent.com/22987140/52713067-aa48ac00-2f96-11e9-968b-3794bb33a53c.png)

Ich hoffe das ganze ist verständlich erklärt und funktioniert so. Bei Fragen könnt ihr euch gerne an mich @adrianjost wenden.
